name: CI / CD Pipeline
run-name: ${{ github.actor }} is Deploying 

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push result service
        uses: docker/build-push-action@v6
        with:
          context: "./Multi-Stack-Voting-Application/result"
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/result:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/result:latest

      - name: Build and push Worker service
        uses: docker/build-push-action@v6
        with:
          context: "./Multi-Stack-Voting-Application/worker"
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/worker:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/worker:latest

      - name: Build and push vote service
        uses: docker/build-push-action@v6
        with:
          context: "./Multi-Stack-Voting-Application/vote"
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/vote:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/vote:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.0/2024-12-20/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin
          mv ./kubectl $HOME/bin/kubectl
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install voting-app ./helm-chart \
            --namespace default \
            --set image.vote=${{ secrets.DOCKER_USERNAME }}/vote:${{ env.IMAGE_TAG }} \
            --set image.worker=${{ secrets.DOCKER_USERNAME }}/worker:${{ env.IMAGE_TAG }} \
            --set image.result=${{ secrets.DOCKER_USERNAME }}/result:${{ env.IMAGE_TAG }} \
